<?php
    $pagina = "<br><h1>Conceitos</h1>";
    include_once('_head.php');
    include_once('_navbar.php');
?>
<br>
<p class="classifica">
<b>Acordo setorial</b>:<br> ato de natureza contratual firmado entre o poder público e fabricantes, importadores, distribuidores ou comerciantes, tendo em vista a implantação da responsabilidade compartilhada pelo ciclo de vida do produto.<br><br>
<b>Área contaminada</b>:<br> local onde há contaminação causada pela disposição, regular ou irregular, de quaisquer substâncias ou resíduos. <br><br>
<b>Agentes biológicos</b>:<br> microrganismos capazes ou não de originar algum tipo de infecção, alergia ou toxicidade no corpo humano, tais como</b>:<br> bactérias, fungos, vírus, clamídias, riquétsias, micoplasmas, parasitas e outros agentes, linhagens celulares, príons e toxinas. <br><br>
<b>Área órfã contaminada</b>:<br> área contaminada cujos responsáveis pela disposição não sejam identificáveis ou individualizáveis. <br><br>
<b>Armazenamento externo</b>:<br> guarda dos coletores de resíduos em ambiente exclusivo, com acesso facilitado para a coleta externa. <br><br>
<b>Armazenamento interno</b>:<br> guarda do resíduo contendo produto químico ou rejeito radioativo na área de trabalho, em condições definidas pela legislação e normas aplicáveis a essa atividade. <br><br>
<b>Armazenamento temporário</b>:<br> guarda temporária dos coletores de resíduos de serviços de saúde, em ambiente próximo aos pontos de geração, visando agilizar a coleta no interior das instalações e otimizar o deslocamento entre os pontos geradores e o ponto destinado à apresentação para coleta externa. <br><br>
<b>Autodepuração</b>:<br> processo natural decorrente da oxigenação que ocorre num corpo d’água, que permite absorver poluentes e restabelecer o equilíbrio do meio aquático. A autodepuração depende do volume e características do poluente e da capacidade de regeneração do corpo receptor.<br><br>
<b>Aterro sanitário</b>:<br> local utilizado para disposição final do lixo, onde são aplicados critérios de engenharia e normas operacionais específicas para confinar os resíduos com segurança, do ponto de vista do controle da poluição ambiental e proteção à saúde pública.<br><br>
<b>Aquecimento global</b>:<br> é o resultado da intensificação do efeito estufa natural, ocasionado pelo significativo aumento das concentrações de gases do efeito estufa (GEE) na atmosfera, ou seja, gases que absorvem parte do calor que deveria ser dissipado, provocando aumento da temperatura média do planeta. As mudanças climáticas são consequência do aquecimento global, pois com a elevação da temperatura média ocorre maior derretimento de geleiras em regiões polares e de grande altitude, ocasionando a dilatação dos oceanos, mudanças nos ciclos hidro-geológicos e fenômenos atmosféricos adversos. <br><br>
<b>Carcaça de animal</b>:<br> produto proveniente de retalhação de animal. <br><br>
<b>Cadáver de animal</b>:<br> corpo animal após a morte;<br><br>
<b>Chorume</b>:<br> líquido de cor escura, gerado a partir da decomposição da matéria orgânica existente no lixo, que apresenta alto potencial poluidor da água e do solo.<br><br>
<b>Ciclo de vida do produto</b>:<br> é uma série de etapas que envolvem o desenvolvimento do produto, a obtenção de matérias-primas e insumos, o processo produtivo, o consumo e a disposição final.<br><br>
<b>Coleta seletiva</b>:<br> coleta de resíduos sólidos previamente segregados conforme sua constituição ou composição.<br><br>
<b>Compostagem</b>:<br> processo biológico que acelera a decomposição do material orgânico, tendo como produto final o composto orgânico. <br><br>
<b>Controle social</b>:<br> conjunto de mecanismos e procedimentos que garantam à sociedade informações e participação nos processos de formulação, implementação e avaliação das políticas públicas relacionadas aos resíduos sólidos.<br><br>
<b>Economia circular</b>:<br> transforma o modelo linear (extrair – transformar – descartar) em um modelo circular de produção no qual os materiais retornam ao ciclo produtivo ao invés de serem descartados como lixo, dentre outras maneiras, por meio da logística reversa, com a reutilização, a recuperação e a reciclagem de materiais, atingindo assim o chamado ciclo fechado de produção. Seu objetivo é manter produtos, componentes e materiais em seu mais alto nível de utilidade e valor o tempo todo. O conceito distingue os ciclos técnicos dos biológicos.<br><br>
<b>Efeito estufa</b>:<br> fenômeno natural pelo qual parte da radiação solar que chega à superfície da Terra é retida nas camadas baixas da atmosfera, proporcionando a manutenção de temperaturas numa faixa adequada para permitir a vida de milhares de espécies no planeta. Entretanto, devido ao aumento da concentração de gases causadores do efeito estuga (GEE) na atmosfera, tem ocorrido uma maior retenção dessa radiação na forma de calor, e consequentemente, a temperatura média no planeta está aumentando, provocando o aquecimento global e significativas mudanças climáticas.<br><br>
<b>Destinação final ambientalmente adequada</b>:<br> destinação de resíduos que inclui a reutilização, a reciclagem, a compostagem, a recuperação e o aproveitamento energético ou outras destinações admitidas pelos órgãos competentes do Sistema Nacional do Meio Ambiente (Sisnama), do Sistema Nacional de Vigilância Sanitária (SNVS) e do Sistema Unificado de Atenção à Sanidade Agropecuária (Suasa), entre elas a disposição final ambientalmente adequada, observando normas operacionais específicas de modo a evitar danos ou riscos à saúde pública e à segurança e a minimizar os impactos ambientais adversos. <br><br>
<b>Disposição final ambientalmente adequada</b>:<br> distribuição ordenada de rejeitos em aterros, observando normas operacionais específicas de modo a evitar danos ou riscos à saúde pública e à segurança e a minimizar os impactos ambientais adversos. <br><br>
<b>Equipamento de proteção individual (EPI)</b>:<br> dispositivo ou produto de uso individual utilizado pelo trabalhador, destinado à proteção de riscos suscetíveis de ameaçar a segurança e a saúde no trabalho. <br><br>
<b>Equipamento de proteção coletiva (EPC)</b>:<br> dispositivos ou produtos de uso coletivo utilizados pelo trabalhador, destinados à proteção de riscos suscetíveis de ameaçar a segurança e a saúde no trabalho e de terceiros. <br><br>
<b>Ficha de informações de segurança de produtos químicos (FISPQ)</b>:<br> ficha que contém informações essenciais detalhadas dos produtos químicos, especialmente sua identificação, seu fornecedor, sua classificação, sua periculosidade, as medidas de precaução e os procedimentos em caso de emergência. <br><br>
<b>Geradores de resíduos sólidos</b>:<br> são os gases listados no Anexo A do Protocolo de Kyoto, sejam</b>:<br> dióxido de carbono (CO2); metano (CH4); óxido nitroso (N2O); hexafluoreto de enxofre (SF6); gases da família dos hidrofluorcarbonos (HFCs) e perfluorcarbonos (PFCs). Conforme especificação do Protocolo, as partes também devem informar a emissão dos seguintes GEE indiretos</b>:<br> monóxido de carbono (CO); óxidos de nitrogênio (NOx); compostos orgânicos voláteis sem metano (NMVOCs) e óxido de enxofre (SOx). As emissões de GEEs são provenientes de processos artificiais, causados pelo homem, como desmatamentos, queima de combustíveis fosseis, emissões de gases e poluentes de indústrias e, também, podem ter origem natural, como emissão de metano por rebanhos, por exemplo.<br><br>
<b>Gerenciamento de resíduos sólidos</b>:<br> conjunto de ações exercidas, direta ou indiretamente, nas etapas de coleta, transporte, transborda, tratamento e destinação final ambientalmente adequada dos resíduos sólidos e disposição final ambientalmente adequada dos rejeitos, de acordo com plano municipal de gestão integrada de resíduos sólidos ou com plano de gerenciamento de resíduos sólidos, exigidos na forma da Lei. <br><br>
<b>Gestão de resíduos</b>:<br> conjunto de ações voltadas para a busca de soluções para os resíduos sólidos, de forma a considerar as dimensões política, econômica, ambiental, cultural e social, com controle social e sob a premissa do desenvolvimento sustentável. <br><br>
<b>Lixiviação</b>:<br> processo pelo qual a matéria orgânica e os sais minerais são removidos do solo, de forma dissolvida, pela percolação da água da chuva.<br><br>
<b>Logística reversa</b>:<br> instrumento de desenvolvimento econômico e social caracterizado por um conjunto de ações, procedimentos e meios destinados a viabilizar a coleta e a restituição dos resíduos sólidos ao setor empresarial, para reaproveitamento, em seu ciclo ou em outros ciclos produtivos, ou outra destinação final ambientalmente adequada. <br><br>
<b>Patogenicidade</b>:<br> é a capacidade que tem o agente infeccioso de, uma vez instalado no organismo do homem e dos animais, produzir sintomas em maior ou menor proporção dentre os hospedeiros infectados. <br><br>
<b>Periculosidade</b>:<br> qualidade ou estado de ser perigoso. <br><br>
<b>Plano de gerenciamento dos resíduos de serviços de saúde (PGRSS)</b>:<br> documento que aponta e descreve todas as ações relativas ao gerenciamento dos resíduos de serviços de saúde, observadas suas características e riscos, contemplando os aspectos referentes à geração, identificação, segregação, acondicionamento, coleta, armazenamento, transporte, destinação e disposição final ambientalmente adequada, bem como as ações de proteção à saúde pública, do trabalhador e do meio ambiente. <br><br>
<b>Plano de proteção radiológica (PPR)</b>:<br> documento exigido para fins de licenciamento de instalações radiativas, pela Comissão Nacional de Energia Nuclear (CNEN).<br><br>
<b>Reciclagem</b>:<br> processo de transformação dos resíduos sólidos que envolve a alteração de suas propriedades físicas, físicoquímicas ou biológicas, com vistas à transformação em insumos ou novos produtos.<br><br>
<b>Recipiente vazio de medicamento</b>:<br> embalagem primária de medicamentos usada em sua preparação ou administração, que tenha sido esvaziado em decorrência da total utilização ou transferência de seu conteúdo deste para outro recipiente. <br><br>
<b>Redução de carga microbiana</b>:<br> aplicação de processo que visa à inativação microbiana das cargas biológicas contidas nos resíduos. <br><br>
<b>Rejeitos</b>:<br> resíduos sólidos que, depois de esgotadas todas as possibilidades de tratamento e recuperação por processos tecnológicos disponíveis e economicamente viáveis, não apresentem outra possibilidade que não a disposição final ambientalmente adequada.<br><br>
<b>Rejeito radioativo</b>:<br> material que contenha radionuclídeo em quantidade superior aos limites de dispensa especificados nas normas da Comissão Nacional de Energia Nuclear (CNEN), para o qual a reutilização é imprópria ou não prevista. <br><br>
<b>Resíduos de serviços de saúde (RSS)</b>:<br> todos os resíduos resultantes das atividades exercidas pelos geradores de resíduos de serviços de saúde, definidos nesta Resolução. <br><br>
<b>Resíduo perigoso</b>:<br> aquele que, em razão de suas características de inflamabilidade, corrosividade, reatividade, toxicidade, patogenicidade, carcinogenicidade, teratogenicidade e mutagenicidade, apresenta significativo risco à saúde pública ou à qualidade ambiental ou à saúde do trabalhador, de acordo com lei, regulamento ou norma técnica. <br><br>
<b>Resíduo sólido</b>:<br> material, substância, objeto ou bem descartado, resultante de atividades humanas em sociedade, a cuja destinação se propõe proceder ou se está obrigado a proceder, nos estados sólido ou semissólido, bem como gases contidos em recipientes e líquidos cujas particularidades tornem inviável o seu lançamento na rede pública de esgotos ou em corpos d'água, ou exijam para isso soluções técnica ou economicamente inviáveis em face da melhor tecnologia disponível. <br><br>
<b>Resíduos de serviços de saúde do Grupo A</b>:<br> resíduos com a possível presença de agentes biológicos que, por suas características, podem apresentar risco de infecção, elencados no Anexo I da Resolução 222 de 2018. <br><br>
<b>Resíduos de serviços de saúde do Grupo B</b>:<br> resíduos contendo produtos químicos que podem apresentar risco à saúde pública ou ao meio ambiente, dependendo de suas características de inflamabilidade, corrosividade, reatividade e toxicidade, elencados no Anexo I da Resolução 222 de 2018. <br><br>
<b>Resíduos de serviços de saúde do Grupo C</b>:<br> rejeitos radioativos, elencados no Anexo I da Resolução 222 de 2018.<br><br>
<b>Responsabilidade compartilhada pelo ciclo de vida do produto</b>:<br> conjunto de atribuições individualizadas e encadeadas dos fabricantes, importadores, distribuidores e comerciantes, dos consumidores e dos titulares dos serviços públicos de limpeza urbana e de manejo dos resíduos sólidos, para minimizar o volume de resíduos sólidos e rejeitos gerados, bem como para reduzir os impactos causados à saúde humana e à qualidade ambiental decorrentes do ciclo de vida dos produtos. <br><br>
<b>Resíduos de serviços de saúde do Grupo D</b>:<br> resíduos que não apresentam risco biológico, químico ou radiológico à saúde ou ao meio ambiente, podendo ser equiparados aos resíduos domiciliares, elencados no Anexo I da Resolução 222 de 2018. <br><br>
<b>Resíduos de serviços de saúde do Grupo E</b>:<br> resíduos perfurocortantes ou escarificantes, tais como</b>:<br> lâminas de barbear, agulhas, escalpes, ampolas de vidro, brocas, limas endodônticas, fios ortodônticos cortados, próteses bucais metálicas inutilizadas, pontas diamantadas, lâminas de bisturi, lancetas, tubos capilares, micropipetas, lâminas e lamínulas, espátulas e todos os utensílios de vidro quebrados no laboratório (pipetas, tubos de coleta sanguínea e placas de Petri), elencados no Anexo I da Resolução 222 de 2018.<br><br>
<b>Reutilização</b>:<br> processo de aproveitamento dos resíduos sólidos sem sua transformação biológica, física ou físico-química.<br><br>
<b>Sistema de Coleta Mista</b>:<br> é a coleta de resíduos heterogêneos, ou seja, a coleta que não distingue o tipo de resíduo. Esse sistema é comum em todo o Brasil e dificulta o processo de reciclagem. Em alguns países da Europa já existe a coleta seletiva, onde os resíduos são coletados já pré-segregados. <br><br>
<b>Segregação</b>:<br> separação dos resíduos, conforme a classificação dos Grupos estabelecida no Anexo I da Resolução 222 de 2018, no momento e local de sua geração, de acordo com as características físicas, químicas, biológicas, o seu estado físico e os riscos envolvidos. <br><br>
<b>Transporte interno</b>:<br> traslado dos resíduos dos pontos de geração até o abrigo temporário ou o abrigo externo. <br><br>
<b>Tratamento</b>:<br> etapa da destinação que consiste na aplicação de processo que modifique as características físicas, químicas ou biológicas dos resíduos, reduzindo ou eliminando o risco de dano ao meio ambiente ou à saúde pública. <br><br>
<b>Unidade geradora de resíduos de serviço de saúde</b>:<br> unidade funcional dentro do serviço no qual é gerado o resíduo.<br><br>
</p>
</div>